name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  build-binary:
    name: Build Executable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true

    - name: Set up store cache
      uses: actions/cache@v2
      with:
        path: store-cache
        key: ghc8107

    - name: Generate executable
      run: nix build .#default -L

    - name: Package executable
      run: |
        cp result/bin/brainfuck brainfuck
        nix shell nixpkgs#patchelf
        sudo patchelf brainfuck --set-interpreter /usr/lib64/ld-linux-x86-64.so.2
        tar -czvf brainfuck.tar.gz brainfuck

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: brainfuck.tar.gz

  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true

    - name: Set up store cache
      uses: actions/cache@v2
      with:
        path: store-cache
        key: ghc8107

    - name: Generate documentation
      run: nix build .#default.doc -L

    - name: Prepare documentation
      run: cp -r ./result-doc/share/doc/*/html .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: haddock
        path: html

  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

  upload-binary:
    name: Upload Documentation
    runs-on: ubuntu-latest
    needs: [build-binary, release]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: executable
        path: brainfuck.tar.gz

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./brainfuck.tar.gz
        asset_name: brainfuck-${{ github.ref }}-linux-x86_64.tar.gz
        asset_content_type: application/gzip

  upload-docs:
    name: Upload Documentation
    runs-on: ubuntu-latest
    needs: [build-docs, release]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: haddock
        path: html

    - name: Upload
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: html
        target_branch: docs
        keep_history: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
